name: Static analysis

on:
  workflow_call:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.5"
          cache: poetry
      - name: Install dependencies
        run: poetry --ansi install
      - name: Run static analysis
        run: poetry run poe check
